import os
from fastapi import FastAPI, Depends, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from sqlalchemy.orm import Session
from sqlalchemy import desc

from database import SessionLocal
from models.site import Site
from models.observation import Observation
from models.anomaly_score import AnomalyScore

app = FastAPI(title="AquaWatch AI API")

# Setup CORS to allow Next.js frontend to communicate
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # Allow all for hackathon
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Serve static files (Before/After images generated by T08)
static_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static")
os.makedirs(static_dir, exist_ok=True)
app.mount("/static", StaticFiles(directory=static_dir), name="static")

# Database Dependency
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/")
def read_root():
    return {"message": "AquaWatch AI API is running"}

@app.get("/api/sites")
def get_sites(db: Session = Depends(get_db)):
    """
    Returns a list of all monitored sites along with their latest anomaly scores.
    """
    sites = db.query(Site).all()
    
    results = []
    for site in sites:
        # Get the latest anomaly score
        score = db.query(AnomalyScore).filter(AnomalyScore.site_id == site.id).order_by(desc(AnomalyScore.computed_at)).first()
        
        results.append({
            "id": site.id,
            "name": site.name,
            "latitude": site.latitude,
            "longitude": site.longitude,
            "site_type": site.site_type,
            "description": site.description,
            "image_before_url": site.image_before_url,
            "image_after_url": site.image_after_url,
            "anomaly_score": {
                "score": score.score if score else None,
                "severity": score.severity if score else None,
                "verdict_text": score.verdict_text if score else None
            } if score else None
        })
        
    return results

@app.get("/api/sites/{site_id}")
def get_site_details(site_id: int, db: Session = Depends(get_db)):
    """
    Returns full details for a specific site, including its time-series observations for charts.
    """
    site = db.query(Site).filter(Site.id == site_id).first()
    if not site:
        raise HTTPException(status_code=404, detail="Site not found")
        
    score = db.query(AnomalyScore).filter(AnomalyScore.site_id == site.id).order_by(desc(AnomalyScore.computed_at)).first()
    observations = db.query(Observation).filter(Observation.site_id == site.id).order_by(Observation.date).all()
    
    obs_list = []
    for obs in observations:
        obs_list.append({
            "date": obs.date.isoformat(),
            "ndwi": obs.ndwi,
            "ndvi": obs.ndvi,
            "cloud_cover_pct": obs.cloud_cover_pct
        })
        
    return {
        "id": site.id,
        "name": site.name,
        "latitude": site.latitude,
        "longitude": site.longitude,
        "site_type": site.site_type,
        "description": site.description,
        "image_before_url": site.image_before_url,
        "image_after_url": site.image_after_url,
        "anomaly_score": {
            "score": score.score,
            "severity": score.severity,
            "verdict_text": score.verdict_text,
            "baseline_mean": score.baseline_mean,
            "baseline_std": score.baseline_std,
            "current_value": score.current_value,
            "metric_used": score.metric_used,
            "computed_at": score.computed_at.isoformat() if score.computed_at else None
        } if score else None,
        "observations": obs_list
    }
